re-enable libsanitizer for thead toolchain and other fixes
* don't include the latest glibc commit that reverted the necessary
  ld.so path additions
* fix build caused by overly long names in gnu-names.h

```c
 #define LD_LINUX_RISCV64V0P7_XTHEAD_LP64D_SO"ld-linux-riscv64v0p7_xthead-lp64d.so.1"
```

```
[ALL  ]      In file included from /work/riscv64-plctxthead-linux-gnu/build/build-libc/multilib_lib64v0p7_xthead_lp64d/gnu/lib-names.h:19,
[ALL  ]                       from ../sysdeps/gnu/unwind-resume.c:22:
[ERROR]      /work/riscv64-plctxthead-linux-gnu/build/build-libc/multilib_lib64v0p7_xthead_lp64d/gnu/lib-names-lp64d.h:6:9: error: ISO C99 requires whitespace after the macro name [-Werror]
[ALL  ]          6 | #define LD_LINUX_RISCV64V0P7_XTHEAD_LP64D_SO"ld-linux-riscv64v0p7_xthead-lp64d.so.1"
[ALL  ]            |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ALL  ]      cc1: all warnings being treated as errors
```